integrate eslint with extends airbnb-base, write some rule and change…
isheraz/mean-stack pull request #18
Opened 2020-12-21 14:18 UTC by muzammal-invozone

… filename

2020-12-21 19:55 UTC, isheraz requested changes

2020-12-21 19:55 UTC, isheraz commented on index.js
> +// var count = 1;
Remove all commented code before commiting.

2020-12-21 19:55 UTC, isheraz commented on index.js
> +let counts = 1;
Can you explain what we're doing here???

2020-12-21 19:55 UTC, isheraz commented on test_lint.js
> +// var count = 1;
remove test files

2020-12-21 19:55 UTC, isheraz commented on package.json
>      "precommit": "echo 'working'"
fix the pre-commit hook to console.log(); env variables

2020-12-22 06:34 UTC, muzammal-invozone commented on index.js
> +let counts = 1;
we used no-var airbnb rule, it is the true case that we are initializing a variable with let keyword.

2020-12-24 11:25 UTC, isheraz approved these changes

2020-12-26 11:02 UTC, isheraz approved these changes

2020-12-26 11:03 UTC, merged