team crud is completed
isheraz/mean-stack pull request #26
Opened 2020-12-23 13:00 UTC by ismail-raza

2020-12-24 10:55 UTC, isheraz requested changes

2020-12-24 10:55 UTC, isheraz commented on .idea/mean-stack.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Add this file to gitignore

2020-12-24 10:55 UTC, isheraz commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
All IDE related files should always be ignored.

2020-12-24 10:55 UTC, isheraz commented on config/config.js
> +require('dotenv').config();
Please Rebase with Staging and use the configuration from there.

2020-12-24 11:02 UTC, isheraz requested changes

2020-12-24 11:02 UTC, isheraz commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this as well, please.

2020-12-24 11:04 UTC, isheraz commented
Please see the conflicts and resolve those.

2020-12-24 11:11 UTC, ismail-raza commented
> Please see the conflicts and resolve those.

OK

2020-12-26 10:40 UTC, isheraz requested changes

2020-12-26 10:40 UTC, isheraz commented on app.js
>  //  checkPermission('Users'),
No commented code should be part of the commit without a // TODO

2020-12-26 10:40 UTC, isheraz commented on constants.js
> +const PG_PORT = process.env.PG_PORT || 5432;
I believe the default port is 45775, please revert and do not change the default port

2020-12-26 10:40 UTC, isheraz commented on controllers/team.controller.js
> +        defaultResponse().error({message:exception.message}, res, responseStatus.ERROR)
Please ensure the message and error sent here as a response is known and has an error code.

2020-12-26 10:40 UTC, isheraz commented on controllers/team.controller.js
> +        if (team) {
checking for object validation should always be 
`if (!team) return res.status(404).message('team with id not found')` or similar

2020-12-26 10:40 UTC, isheraz commented on controllers/team.controller.js
> +        if (team) {
similar for all requests. 
Also please add validation for each param.

2020-12-26 10:40 UTC, isheraz commented on models/Team.js
> +// const Sequelize = require('sequelize');
Remove Comments

2020-12-26 10:40 UTC, isheraz commented on package.json
> -  "husky": {
Please do not remove `husky` or pre-commit actions, add these back.

2020-12-26 10:41 UTC, isheraz commented
Also, delete and create a new branch from origin since I removed the .idea directory for you. additionally, rebase all your commits into one.

2020-12-28 13:19 UTC, isheraz requested changes
Please Make Sure you run 
`git branch -D staging && git fetch --all && git checkout -b staging origin/staging && git checkout team && git rebase staging` and resolve all conflicts with latest changes.

2020-12-29 07:13 UTC, isheraz requested changes

2020-12-29 07:13 UTC, isheraz commented on _helpers/basicAuth.js
> +  //   userPermission[] = [userPermission];
Remove Comments

2020-12-29 07:13 UTC, isheraz commented on migrations/20201223081551-team.js
> +<<<<<<< HEAD
Fix this merge issue

2020-12-29 07:13 UTC, isheraz commented on migrations/20201223081551-team.js
> +            members: Sequelize.STRING,
Adjust as needed for grouping team

2020-12-30 11:56 UTC, merged